### ISSUE TITLE
Using attributes like customTrackDrawable and customThumbDrawable does not have any effect on scrollbar

### ISSUE THREAD

**Issue by jianinz** [hieupham1993/android-standalone-scroll-bar#1]
Hi,

Integrating your library which seems to work well, Though when customising the scrollbar horizontally, even if setting attributes like customTrackDrawable and customThumbDrawable, it does not have any effect on scrollbar at all

**Comment by hieupham1993** [comment]
Hi @jianinz 
Can you describe more detail about your issue?

**Comment by jianinz** [comment]
@hieupham1993 thanks for getting back to me. In the README https://github.com/hieupham1993/android-standalone-scroll-bar#customization part, it says that user could customize track and thumb drawable by doing
```
scrollbar.customTrackDrawable = customDrawable
scrollbar.customThumbDrawable = customDrawable
```

When doing so in my fragment, i don't see any changes of track nor thumb in UI. Eventually what i did is to use xml attributes settings, and that actually works
```
          app:scrollbarTrackDrawable="@drawable/scrollbar_background"
          app:scrollbarThumbDrawable="@drawable/scrollbar_thumbnail"

```

Should i close this issue or would you like to take a look at why it's not working as intended? Or am i interpreting the usage of customTrackDrawable and customThumbDrawable wrong?

**Comment by hieupham1993** [comment]
@jianinz Glad to hear your problem solved :)
I've tried to use those properties myself and they did works. I'm not sure why they did not work in your case.

**Comment by jianinz** [comment]
Then will close this for now, thanks
